# Generated by Django 4.0.6 on 2022-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_commit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
