# Generated by Django 4.0.6 on 2022-07-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_repo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='email',
            field=models.EmailField(default='mail@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='files_changed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
